apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    operated-prometheus: "true"  # Added label for Prometheus scraping
spec:
  selector:
    app: nginx
  ports:
    - name: nginx-web-service
      protocol: TCP
      port: 7800
      targetPort: 7800
    - name: nginx-metrics-service
      protocol: TCP
      port: 9113
      targetPort: 9113
  type: LoadBalancer
