apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0 # Specify your preferred Redis version
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config-volume
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
      volumes:
        - name: redis-config-volume
          configMap:
            name: redis-config