apiVersion: v1
kind: Service
metadata:
  name: llm-api
  namespace: default
  labels:
    operated-prometheus: "true"  # Added label for Prometheus scraping
spec:
  selector:
    app: llm-api
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
