apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    operated-prometheus: "true"  # Added label for Prometheus scraping
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 7800
      targetPort: 7800
  type: LoadBalancer
