apiVersion: v1
kind: Service
metadata:
  name: qa-ui
  namespace: default
  labels:
    operated-prometheus: "true"  # Added label for Prometheus scraping
spec:
  selector:
    app: qa-ui
  ports:
    - name: qa-ui-service
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: prometheus-exporter
      protocol: TCP
      port: 9100
      targetPort: 9100

